title: Harry Wojtas
description: Ceramics, block prints, and photography by Harry Wojtas
url: "https://harrisonwojtas.github.io"
baseurl: "/Website"

markdown: kramdown
plugins:
  - jekyll-sitemap

exclude:
  - README.md